<?php
return array (
  2 => 
  array (
    'id' => '2',
    'catid' => '6',
    'typeid' => '0',
    'title' => '321321',
    'style' => '',
    'thumb' => '',
    'keywords' => '123213213213',
    'description' => '123123',
    'posids' => '0',
    'url' => 'http://phpcms/index.php?m=content&c=index&a=show&catid=6&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1415946132',
    'updatetime' => '1420433688',
    'hitsid' => 'c-1-2',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '6',
    'typeid' => '0',
    'title' => '1231',
    'style' => '',
    'thumb' => '',
    'keywords' => '1231',
    'description' => '3213213',
    'posids' => '0',
    'url' => 'http://phpcms/index.php?m=content&c=index&a=show&catid=6&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1415946087',
    'updatetime' => '1415946096',
    'hitsid' => 'c-1-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>